# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  run-automation-regression-tests:
    runs-on: windows-latest
    steps:
        - run: git config --global url."https://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@github.com/".insteadOf https://github.com/
        - name: Checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false
        - name: Setup node
          uses: actions/setup-node@v2
          with:
            node-version: '14.15'
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Cypress run
          uses: cypress-io/github-action@v4.1.0
          with:
            browser: chrome

        - name: Upload MP4 files
          uses: actions/upload-artifact@v2
          with:
            name: mp4-files
            path: mp4_files
            
